### ISSUE TITLE
forges problem

### ISSUE THREAD

**Issue by ltspicer** [Aermoss/Aerics#2]
pip install forges

$ ./client.py

UserWarning: Using SDL2 binaries from pysdl2-dll 2.30.2
Traceback (most recent call last):
  File "/home/yyy/python.kurs/aerics/./client.py", line 3, in <module>
    import forges, aerics, sys
  File "/home/yyy/.local/lib/python3.12/site-packages/forges/__init__.py", line 23, in <module>
    fonts = FontManager(forges).get()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yyy/.local/lib/python3.12/site-packages/forges/font_manager.py", line 21, in get
    for file in os.listdir(self.path):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/yyy/.local/lib/python3.12/site-packages/forges\\assets\\fonts'

It looks like the module uses the Windows syntax ( \ instead of / )
If I replace all \\ with / in font_manager, it appears:

UserWarning: Using SDL2 binaries from pysdl2-dll 2.30.2
Traceback (most recent call last):
  File "/home/yyy/python.kurs/aerics/./client.py", line 39, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/home/yyy/python.kurs/aerics/./client.py", line 34, in main
    window = Window()
             ^^^^^^^^
  File "/home/yyy/python.kurs/aerics/./client.py", line 7, in __init__
    super(Window, self).__init__()
  File "/home/yyy/.local/lib/python3.12/site-packages/forges/window.py", line 21, in __init__
    self.user32 = ctypes.windll.user32
                  ^^^^^^^^^^^^^
AttributeError: module 'ctypes' has no attribute 'windll'

What do I have to install to run "forges" in Linux?

**Comment by Aermoss** [comment]
I have released a new version, it should have solved your problem.
